# Generated by Django 3.2.7 on 2021-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=50)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('LabourName', models.CharField(blank=True, max_length=50)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
