# Generated by Django 3.2.7 on 2021-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='Payer',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='Proof',
            field=models.FileField(null=True, upload_to='proof/'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='Unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
