# Generated by Django 3.2.7 on 2021-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0002_auto_20210908_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='Payer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
