# Generated by Django 3.2.7 on 2021-09-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0003_alter_revenue_payer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='Proof',
            new_name='Doc',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='Payer',
            new_name='PayerName',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='Unit',
            new_name='UnitNumber',
        ),
    ]
