# Generated by Django 3.2.7 on 2021-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0004_auto_20210908_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to='proof/'),
        ),
    ]
