# Generated by Django 3.2.7 on 2021-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0011_auto_20210909_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='Doc',
            field=models.ImageField(blank=True, null=True, upload_to='proof/'),
        ),
    ]
