# Generated by Django 3.2.7 on 2021-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0013_auto_20210911_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='PayerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='UnitNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
