# Generated by Django 3.2.7 on 2021-09-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0014_auto_20210912_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expend',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='labour',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='DateTime',
        ),
    ]
