# Generated by Django 3.2.7 on 2021-09-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0015_auto_20210915_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='PriceAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='数目'),
        ),
    ]
