# Generated by Django 3.2.7 on 2021-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0016_alter_revenue_priceamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expend',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to='proof/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='expend',
            name='PriceAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='expend',
            name='Supplier',
            field=models.CharField(blank=True, max_length=50, verbose_name='供货商'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='LabourName',
            field=models.CharField(blank=True, max_length=50, verbose_name='工人姓名'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='PriceAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='数目'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='Doc',
            field=models.ImageField(blank=True, null=True, upload_to='proof/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='PayerName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='UnitNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='单元'),
        ),
    ]
