# Generated by Django 3.2.7 on 2021-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0017_auto_20210925_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='PayerName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='顾客姓名'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='UnitNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='顾客单元'),
        ),
    ]
