# Generated by Django 3.2.7 on 2021-09-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0018_auto_20210925_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
